# Summary of Deer Harvested by Season and Year 1972-73 Through 2019-20

In [87]:
#Import Dependencies
import pandas as pd
import os

In [88]:
#File paths
tables = pd.read_html("https://www.state.nj.us/dep/fgw/deerharvestsummary.htm")
summary_data =  os.path.join("","Resources","summaryData","summaryDeerHarvested_Season_Year.csv")

In [59]:
#Create data frame from the html content
deerHarvestedSeason=pd.DataFrame(tables[6])

In [60]:
#Sample data
deerHarvestedSeason.head(5)

,0,1,2,3,4,5,6,7,8,9,10
0,Season,Fall Bow,Youth Hunts,Permit Bow,Six-day Firearm,Permit Muzzleloader,Permit Shotgun,Winter Bow,Total Harvest,Antlered Harvest,Antlerless Harvest
1,1972-73,1464,NaN,NaN,6994,NaN,2563,NaN,11021,7763,3258
2,1973-74,1689,NaN,NaN,6837,NaN,2792,NaN,11318,7722,3596
3,1974-75,1717,NaN,NaN,6995,NaN,4434,NaN,13146,7936,5210
4,1975-76,1823,NaN,NaN,6790,NaN,3885,190,12688,7812,4876

In [61]:
#Get column names
deerHarvestedSeason.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [62]:
#Rename the data frame columns for individual quarter data
deerHarvestedSeason= deerHarvestedSeason.rename(columns={0: "Season", 1: "Fall Bow",
                   2:"Youth Hunts",3:"Permit Bow",4:"Six-day Firearm",5:"Permit Muzzleloader",
                    6:"Permit Shotgun",7:"Winter Bow",8:"Total Harvest",9:"Antlered Harvest",
                    10:"Antlerless Harvest"})

In [81]:
#Display sample results
deerHarvestedSeason.head(3)

,Season,Fall Bow,Youth Hunts,Permit Bow,Six-day Firearm,Permit Muzzleloader,Permit Shotgun,Winter Bow,Total Harvest,Antlered Harvest,Antlerless Harvest
1,1972-73,1464,NaN,NaN,6994,NaN,2563,NaN,11021,7763,3258
2,1973-74,1689,NaN,NaN,6837,NaN,2792,NaN,11318,7722,3596
3,1974-75,1717,NaN,NaN,6995,NaN,4434,NaN,13146,7936,5210

In [82]:
#Filter duplicated header rows from the data
deerHarvestedSeason = deerHarvestedSeason[deerHarvestedSeason['Season'] != 'Seasons']

In [85]:
#Fill NA values with 0
deerHarvestedSeason.fillna(0)

,Season,Fall Bow,Youth Hunts,Permit Bow,Six-day Firearm,Permit Muzzleloader,Permit Shotgun,Winter Bow,Total Harvest,Antlered Harvest,Antlerless Harvest
1,1972-73,1464,0,0,6994,0,2563,0,11021,7763,3258
2,1973-74,1689,0,0,6837,0,2792,0,11318,7722,3596
3,1974-75,1717,0,0,6995,0,4434,0,13146,7936,5210
4,1975-76,1823,0,0,6790,0,3885,190,12688,7812,4876
5,1976-77,1960,0,0,7140,0,3768,150,13018,8374,4644
6,1977-78,2381,0,0,7829,0,3999,210,14419,9329,5090
7,1978-79,2361,0,0,7017,249,5911,280,15818,8690,7128
8,1979-80,2020,0,0,8673,387,4783,243,16106,10084,6022
9,1980-81,4853,0,0,9959,648,5423,308,21191,12404,8787
10,1981-82,5520,0,0,10485,989,4817,326,22137,13131,9006
12,1982-83,6587,0,0,10033,1073,5711,341,23745,13527,10218
13,1983-84,6524,0,0,10121,1160,5136,378,23319,13756,9563
14,1984-85,7149,0,0,11030,1631,5259,550,25619,14866,10753
15,1985-86,7535,0,0,11513,2829,7080,435,29392,16417,12975
16,1986-87,7861,0,1768,13758,3488,6344,558,33777,19907,13870
17,1987-88,8483,0,2548,14523,3815,9077,782,39228,22006,17222
18,1988-89,9816,0,2326,14158,4203,14779,618,45900,22544,23356
19,1989-90,10107,0,2952,14018,5899,14895,655,48526,23075,25451
20,1990-91,10422,0,2619,13513,4897,15962,809,48222,23141,25081
21,1991-92,11423,0,3319,11090,4426,14420,738,45416,21882,23534
24,1993-94,13393,0,2953,11895,5739,15302,660,49942,23821,26121
25,1994-95,14396,0,3602,11596,5700,15306,842,51442,24650,26792
26,1995-96,15821,0,3992,14071,7746,17359,780,59769,28073,31696
27,1996-97,11527,0,7327,10035,9580,17094,1141,56704,25992,30712
28,1997-98,12196,0,6977,11518,9831,17941,1088,59551,27211,32340
29,1998-99,12581,0,7228,10921,9850,18268,1166,60014,26989,33025
30,1999-00,14282,0,9583,10848,10920,28498,1267,75398,22035,53363
31,2000-01,13868,0,9429,13016,12470,27116,1545,77444,23307,54137
32,2001-02,13037,730,9726,9977,12357,23060,1083,69970,20734,49236
34,2002-03,11329,783,8657,10524,10166,20678,894,63031,20783,42248
36,2004-05,13128,709,8340,7895,10359,16950,1183,58564,17965,40599
37,2005-06,14040,839,8206,10001,10040,15533,998,59657,20508,39145
38,2006-07,14418,844,7246,9259,9282,14502,1122,56673,19460,37213
39,2007-08,9994,725,6086,8243,8338,12399,1232,47017,17467,29549
40,2008-09,13299,860,6089,7741,9878,13764,1629,53260,18399,34861
41,2009-10,14161,689,6852,8014,7639,13383,2046,52784,19181,33603
42,2010-11,15775,817,8428,7485,7827,12446,2626,55404,19925,35479
43,2011-12,14207,767,8022,7025,6509,10815,2764,50109,18567,31533
45,2012-13,15049,743,7934,6614,6432,10267,2903,49942,17752,32146
46,2013-14,15151,600,10451,6019,6110,10295,2970,51595,18511,33083
48,2015-16,13312,376,7049,4791,4398,8470,3043,41439,15290,26149
49,2016-17,15105,407,10247,6284,4935,9164,3104,49246,19889,29357
50,2017-18,13993,353,10402,6177,5225,9008,3387,48545,20082,28463
51,2018-19,14612,436,10649,7291,4812,9374,3687,50861,21545,29316
52,2019-20,14071,330,11223,4850,4126,7757,3293,45650,18852,26798

In [89]:
#Export data to csv file
deerHarvestedSeason.to_csv(summary_data,index=False)